In [21]:
import pandas as pd

In [22]:
import pandas as pd

patients = pd.read_csv("../data/raw/patients.csv")
doctors = pd.read_csv("../data/raw/doctors.csv")
appointments = pd.read_csv("../data/raw/appointments.csv")
treatments = pd.read_csv("../data/raw/treatments.csv")
billing = pd.read_csv("../data/raw/billing.csv")

In [23]:
print("Patients:", patients.shape)
print("Doctors:", doctors.shape)
print("Appointments:", appointments.shape)
print("Treatments:", treatments.shape)
print("Billing:", billing.shape)

Patients: (50, 11)
Doctors: (10, 8)
Appointments: (200, 7)
Treatments: (200, 6)
Billing: (200, 7)

In [24]:
patients.head()

,patient_id,first_name,last_name,gender,date_of_birth,contact_number,address,registration_date,insurance_provider,insurance_number,email
0,P001,David,Williams,F,1955-06-04,6939585183,789 Pine Rd,2022-06-23,WellnessCorp,INS840674,david.williams@mail.com
1,P002,Emily,Smith,F,1984-10-12,8228188767,321 Maple Dr,2022-01-15,PulseSecure,INS354079,emily.smith@mail.com
2,P003,Laura,Jones,M,1977-08-21,8397029847,321 Maple Dr,2022-02-07,PulseSecure,INS650929,laura.jones@mail.com
3,P004,Michael,Johnson,F,1981-02-20,9019443432,123 Elm St,2021-03-02,HealthIndia,INS789944,michael.johnson@mail.com
4,P005,David,Wilson,M,1960-06-23,7734463155,123 Elm St,2021-09-29,MedCare Plus,INS788105,david.wilson@mail.com

In [25]:
doctors.head()
appointments.head()
treatments.head()
billing.head()

,bill_id,patient_id,treatment_id,bill_date,amount,payment_method,payment_status
0,B001,P034,T001,2023-08-09,3941.97,Insurance,Pending
1,B002,P032,T002,2023-06-09,4158.44,Insurance,Paid
2,B003,P048,T003,2023-06-28,3731.55,Insurance,Paid
3,B004,P025,T004,2023-09-01,4799.86,Insurance,Failed
4,B005,P040,T005,2023-07-06,582.05,Credit Card,Pending

In [26]:
billing.columns

Index(['bill_id', 'patient_id', 'treatment_id', 'bill_date', 'amount',
       'payment_method', 'payment_status'],
      dtype='object')

In [27]:
doctors.columns

Index(['doctor_id', 'first_name', 'last_name', 'specialization',
       'phone_number', 'years_experience', 'hospital_branch', 'email'],
      dtype='object')

In [28]:
appointments.columns

Index(['appointment_id', 'patient_id', 'doctor_id', 'appointment_date',
       'appointment_time', 'reason_for_visit', 'status'],
      dtype='object')

In [29]:
treatments.columns

Index(['treatment_id', 'appointment_id', 'treatment_type', 'description',
       'cost', 'treatment_date'],
      dtype='object')

In [30]:
patients.columns

Index(['patient_id', 'first_name', 'last_name', 'gender', 'date_of_birth',
       'contact_number', 'address', 'registration_date', 'insurance_provider',
       'insurance_number', 'email'],
      dtype='object')

In [31]:
patients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          50 non-null     object
 1   first_name          50 non-null     object
 2   last_name           50 non-null     object
 3   gender              50 non-null     object
 4   date_of_birth       50 non-null     object
 5   contact_number      50 non-null     int64
 6   address             50 non-null     object
 7   registration_date   50 non-null     object
 8   insurance_provider  50 non-null     object
 9   insurance_number    50 non-null     object
 10  email               50 non-null     object
dtypes: int64(1), object(10)
memory usage: 4.4+ KB

In [32]:
doctors.info

<bound method DataFrame.info of   doctor_id first_name last_name specialization  phone_number  \
0      D001      David    Taylor    Dermatology    8322010158
1      D002       Jane     Davis     Pediatrics    9004382050
2      D003       Jane     Smith     Pediatrics    8737740598
3      D004      David     Jones     Pediatrics    6594221991
4      D005      Sarah    Taylor    Dermatology    9118538547
5      D006       Alex     Davis     Pediatrics    6570137231
6      D007     Robert     Davis       Oncology    8217493115
7      D008      Linda     Brown    Dermatology    9069162601
8      D009      Sarah     Smith     Pediatrics    7387087517
9      D010      Linda    Wilson       Oncology    6176383634

   years_experience   hospital_branch                         email
0                17   Westside Clinic  dr.david.taylor@hospital.com
1                24   Eastside Clinic    dr.jane.davis@hospital.com
2                19   Eastside Clinic    dr.jane.smith@hospital.com
3                28  Central Hospital   dr.david.jones@hospital.com
4                26  Central Hospital  dr.sarah.taylor@hospital.com
5                23  Central Hospital    dr.alex.davis@hospital.com
6                26   Westside Clinic  dr.robert.davis@hospital.com
7                 5   Westside Clinic   dr.linda.brown@hospital.com
8                26  Central Hospital   dr.sarah.smith@hospital.com
9                21   Eastside Clinic  dr.linda.wilson@hospital.com  >

In [33]:
appointments.info

<bound method DataFrame.info of     appointment_id patient_id doctor_id appointment_date appointment_time  \
0             A001       P034      D009       2023-08-09         15:15:00
1             A002       P032      D004       2023-06-09         14:30:00
2             A003       P048      D004       2023-06-28          8:00:00
3             A004       P025      D006       2023-09-01          9:15:00
4             A005       P040      D003       2023-07-06         12:45:00
..             ...        ...       ...              ...              ...
195           A196       P045      D006       2023-10-26          9:45:00
196           A197       P001      D005       2023-04-01         13:30:00
197           A198       P022      D006       2023-05-15          8:30:00
198           A199       P017      D001       2023-05-01         12:45:00
199           A200       P007      D005       2023-12-30         10:15:00

    reason_for_visit     status
0            Therapy  Scheduled
1            Therapy    No-show
2       Consultation  Cancelled
3       Consultation  Cancelled
4          Emergency    No-show
..               ...        ...
195          Checkup  Cancelled
196        Emergency    No-show
197          Therapy    No-show
198        Follow-up  Completed
199     Consultation  Cancelled

[200 rows x 7 columns]>

In [34]:
treatments.info

<bound method DataFrame.info of     treatment_id appointment_id treatment_type         description     cost  \
0           T001           A001   Chemotherapy     Basic screening  3941.97
1           T002           A002            MRI   Advanced protocol  4158.44
2           T003           A003            MRI  Standard procedure  3731.55
3           T004           A004            MRI     Basic screening  4799.86
4           T005           A005            ECG  Standard procedure   582.05
..           ...            ...            ...                 ...      ...
195         T196           A196   Chemotherapy   Advanced protocol  2477.80
196         T197           A197  Physiotherapy  Standard procedure   975.49
197         T198           A198            ECG     Basic screening  3383.72
198         T199           A199   Chemotherapy     Basic screening  1472.17
199         T200           A200          X-Ray     Basic screening  3288.15

    treatment_date
0       2023-08-09
1       2023-06-09
2       2023-06-28
3       2023-09-01
4       2023-07-06
..             ...
195     2023-10-26
196     2023-04-01
197     2023-05-15
198     2023-05-01
199     2023-12-30

[200 rows x 6 columns]>

In [35]:
billing.info

<bound method DataFrame.info of     bill_id patient_id treatment_id   bill_date   amount payment_method  \
0      B001       P034         T001  2023-08-09  3941.97      Insurance
1      B002       P032         T002  2023-06-09  4158.44      Insurance
2      B003       P048         T003  2023-06-28  3731.55      Insurance
3      B004       P025         T004  2023-09-01  4799.86      Insurance
4      B005       P040         T005  2023-07-06   582.05    Credit Card
..      ...        ...          ...         ...      ...            ...
195    B196       P045         T196  2023-10-26  2477.80           Cash
196    B197       P001         T197  2023-04-01   975.49           Cash
197    B198       P022         T198  2023-05-15  3383.72           Cash
198    B199       P017         T199  2023-05-01  1472.17    Credit Card
199    B200       P007         T200  2023-12-30  3288.15      Insurance

    payment_status
0          Pending
1             Paid
2             Paid
3           Failed
4          Pending
..             ...
195        Pending
196        Pending
197         Failed
198           Paid
199           Paid

[200 rows x 7 columns]>

In [36]:
patients.isnull().sum()

patient_id            0
first_name            0
last_name             0
gender                0
date_of_birth         0
contact_number        0
address               0
registration_date     0
insurance_provider    0
insurance_number      0
email                 0
dtype: int64

In [37]:
doctors.isnull().sum()

doctor_id           0
first_name          0
last_name           0
specialization      0
phone_number        0
years_experience    0
hospital_branch     0
email               0
dtype: int64

In [38]:
appointments.isnull().sum()

appointment_id      0
patient_id          0
doctor_id           0
appointment_date    0
appointment_time    0
reason_for_visit    0
status              0
dtype: int64

In [39]:
billing.isnull().sum()

bill_id           0
patient_id        0
treatment_id      0
bill_date         0
amount            0
payment_method    0
payment_status    0
dtype: int64

In [40]:
treatments.isnull().sum()

treatment_id      0
appointment_id    0
treatment_type    0
description       0
cost              0
treatment_date    0
dtype: int64